# Generated by Django 6.0.6 on 2026-08-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecttracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
